# Project: œÓƒø4
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = swap.o swap0.o
LINKOBJ  = swap.o swap0.o
LIBS     = -L"D:/÷”»ŸŒ∞.D/±‡≥Ãc++/Dev-Cpp/MinGW64/lib" -L"D:/÷”»ŸŒ∞.D/±‡≥Ãc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/÷”»ŸŒ∞.D/±‡≥Ãc++/Dev-Cpp/MinGW64/include" -I"D:/÷”»ŸŒ∞.D/±‡≥Ãc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/÷”»ŸŒ∞.D/±‡≥Ãc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/÷”»ŸŒ∞.D/±‡≥Ãc++/Dev-Cpp/MinGW64/include" -I"D:/÷”»ŸŒ∞.D/±‡≥Ãc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/÷”»ŸŒ∞.D/±‡≥Ãc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/÷”»ŸŒ∞.D/±‡≥Ãc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = œÓƒø4.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

swap.o: swap.cpp
	$(CPP) -c swap.cpp -o swap.o $(CXXFLAGS)

swap0.o: swap0.cpp
	$(CPP) -c swap0.cpp -o swap0.o $(CXXFLAGS)
